<%
// footer.inc
// Copyright (c) 2000 - 2010 Citrix Systems, Inc. All Rights Reserved.
// Web Interface 5.4.0.0
%>
<div id="footer">
  <div id="footerBegin">
	<div class="footerLinks">
		<h2>More Information</h2>
			<p>&raquo; <a href="http://info.apps.ufl.edu">View the FAQ</a></p>
			<p style="display:none;">&raquo; <a href="#">Read the Wiki</a></p>
	</div>
  </div>
  <div id="monogram"><img src="../media/custom/uf_monogram.png">
	</div>
  <div id="footerAdditional">
	<div id="institutional-footer">
	  <div class="container"><span class="uf-monogram"></span>

		<div id="footer-links" class="span-24 black-25">
			
			<div class="footer_logo">
				<a href="http://www.ufl.edu/"><img src="../media/custom/uf_logo_full.png" alt="University of Florida" /></a>
			</div>
			<ul>
				<li><a href="https://webmail.ufl.edu/">WebMail</a></li>
				<li><a href="https://lss.at.ufl.edu/">eLearning</a></li>
				<li><a href="http://www.isis.ufl.edu/">ISIS</a></li>
				<li><a href="https://my.ufl.edu/ps/signon.html">MyUFL</a></li>
				<li><a href="http://campusmap.ufl.edu/">Campus Map</a></li>
				<li><a href="http://news.ufl.edu/">News</a></li>
				<li><a href="http://calendar.ufl.edu/">Calendar</a></li>
				<li><a href="https://phonebook.ufl.edu/">Directory</a></li>
				<li><a href="http://www.ufl.edu/websites/">Web Site Listing</a></li>
				<li><a href="http://www.questions.ufl.edu/">Ask UF</a></li>
			</ul>
			<ul>
				<li><a href="http://www.ufl.edu/disability/">Disability Services</a></li>
				<li><a href="http://privacy.ufl.edu/privacystatement.html">Privacy Policy</a></li>
				<li><a href="http://regulations.ufl.edu/">Regulations</a></li>
								<li><a id="contact-webmaster" href="mailto:webmaster@ufl.edu">Contact Webmaster</a></li> 				<li><a href='https://www.uff.ufl.edu/OnlineGiving/Advanced.asp'>Make a Gift</a></li>
			</ul>
			<ul>
				<li>&copy; 2013 <a href="http://www.ufl.edu/">University of Florida</a>, Gainesville, FL 32611; (352) 392-3261</li>
				<li>This page uses <a href="http://www.google.com/analytics/">Google Analytics</a> (<a href="http://www.google.com/intl/en_ALL/privacypolicy.html">Google Privacy Policy</a>)</li>
			</ul>

			
			
		  </div>
		</div>
	</div>
<!-- Commented out until moved to production

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37419735-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>-->
</div>
