#headerWrapper{
background-image: -moz-linear-gradient(top, 
							#334a9a, 
							#051c62);
	background-image: -webkit-gradient(linear,left top,left bottom,   
		color-stop(0,   	#334a9a),   
		color-stop(1,   	#051c62));
  	filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#334a9a', EndColorStr='#051c62',GradientType=0);
	border-top: #FD7D00 2px solid;
}

#header{background:transparent;}
.horizonPage, #horizonTop { background: #FFF; }
#horizonTop {display:none;}
#horizonTop img{padding-top:40px;}
.horizonPage .mainPane {width: 900px; margin: 0 auto; margin-top:80px; padding-bottom:10px; top:0; background: url(../media/custom/UF-Apps-CloudGraphic1.png) no-repeat right top }
table.carbonBox {width:auto; margin-top:60px;}
#horizonMainPane{height:415px;}
#horizonTagline{color:#666;}

#footerBegin{
	height:140px; 
	padding-top:20px;
	background-image: -moz-linear-gradient(top, 
							#051c62, 
							#334a9a);
	background-image: -webkit-gradient(linear,left top,left bottom,   
		color-stop(0,   	#051c62),   
		color-stop(1,   	#334a9a));
  	filter: progid:DXImageTransform.Microsoft.gradient(startColorStr='#051c62', EndColorStr='#334a9a',GradientType=0);
	border-bottom: 6px solid #FD7D00;
}

#footerAdditional{
	height:70px;
	background:#FFF;
	margin-top:-25px;
	z-index:-10;
	width:900px;
	margin:0 auto;
}
#footerAdditional ul{
	display:block;
	overflow:hidden;
	
}
#footerAdditional li{
	float: left;
	border-right: 1px solid #7E7E7E;
	font-size:.9em;
	background: none;
	padding: 0 10px 0 0;
	margin-right: 10px;
	margin-top: 6px;
	margin-bottom: 0;
	line-height: 1.2em;
	color: #7E7E7E;
}
#footerAdditional img{
	float: right;
}
#monogram img{
    display: block;
	margin:0 auto;
	margin-top:-25px;
	z-index:100;
}
#horizonTaglineFooter {
  color: #F2F2F2;
  font-size: 180%;
  font-weight: normal;
  padding: 10px;
  text-align: center;
}
.footerLinks{
	width:275px;
	height: 70px;
	margin: 0 auto;
	margin-top:15px;
	color: #F5F5F5;
	text-align: left;
	border-left:1px dotted white;
}
.footerLinks h2{
	font-size:200%;
	padding-left:10px;
}
.footerLinks p{
    font-size:130%;
	color:#F5F5F5 !important;
    padding: 17px !important;
    float:left;
}
.footerLinks a{
	color:#FFF;
}
